name: flutter_steps_tracker
description: an application to track footsteps of users, and build a reward system such that the application will exchange automatically their footsteps into (Health Points)


publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.5
  overlay_support: ^2.0.1
  flutter_svg: ^1.1.0
  percent_indicator: ^4.2.2
  fl_chart: ^0.51.0
  animated_bottom_navigation_bar: ^0.3.3
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  extended_image: ^6.2.1

  # Routing
  auto_route: ^4.0.1

  # functions
  timeago: ^3.2.2
  dartz: ^0.10.1
  pedometer: ^3.0.0

  # Localization
  easy_localization: ^3.0.1

  # State Management
  flutter_riverpod: ^1.0.4

  # Firebase
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_messaging: ^11.4.1


  # data
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15




  # Debugging and testing
  logging: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3





flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/localization/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Jannat
      fonts:
        - asset: assets/fonts/jannat_regular.ttf




#flutter_icons:
#  android: true
#  ios: true
#  image_path: ""
#  image_path_android: ""
#  image_path_ios: ""
#  remove_alpha_ios: true`
